import { Author } from "../types/types";

export const dummyAuthors: Author[] = [
    // {
    //   id: 1,
    //   userId: 101,
    //   biography: 'Renowned artist with a passion for nature and landscapes.',
    //   country: 'United States',
    //   birthDate: '1980-05-15',
    //   socialMediaLinks: 'http://twitter.com/artist1, http://instagram.com/artist1',
    //   numberOfPosts: 25,
    // },
    // {
    //   id: 2,
    //   userId: 102,
    //   biography: 'Experimental artist exploring the boundaries of abstraction.',
    //   country: 'France',
    //   birthDate: '1975-09-22',
    //   socialMediaLinks: 'http://facebook.com/artist2, http://instagram.com/artist2',
    //   numberOfPosts: 18,
    // },
    // {
    //   id: 3,
    //   userId: 103,
    //   biography: 'Passionate about realism and capturing life in its purest form.',
    //   country: 'Italy',
    //   birthDate: '1982-02-10',
    //   socialMediaLinks: 'http://twitter.com/artist3, http://facebook.com/artist3',
    //   numberOfPosts: 30,
    // },
    // {
    //   id: 4,
    //   userId: 104,
    //   biography: 'Specializes in urban art and street murals.',
    //   country: 'Germany',
    //   birthDate: '1978-11-30',
    //   socialMediaLinks: 'http://instagram.com/artist4, http://linkedin.com/artist4',
    //   numberOfPosts: 22,
    // },
    // {
    //   id: 5,
    //   userId: 105,
    //   biography: 'Fascinated by surrealism and dream-like imagery.',
    //   country: 'Spain',
    //   birthDate: '1985-07-18',
    //   socialMediaLinks: 'http://facebook.com/artist5, http://linkedin.com/artist5',
    //   numberOfPosts: 15,
    // },
    // {
    //   id: 6,
    //   userId: 106,
    //   biography: 'Celebrates the beauty of wildlife through intricate illustrations.',
    //   country: 'Canada',
    //   birthDate: '1972-04-05',
    //   socialMediaLinks: 'http://twitter.com/artist6, http://instagram.com/artist6',
    //   numberOfPosts: 27,
    // },
    // {
    //   id: 7,
    //   userId: 107,
    //   biography: 'Innovative sculptor pushing the boundaries of form and material.',
    //   country: 'United Kingdom',
    //   birthDate: '1977-08-12',
    //   socialMediaLinks: 'http://facebook.com/artist7, http://linkedin.com/artist7',
    //   numberOfPosts: 20,
    // },
    // {
    //   id: 8,
    //   userId: 108,
    //   biography: 'Inspired by classical art and mythology, with a modern twist.',
    //   country: 'Greece',
    //   birthDate: '1988-01-25',
    //   socialMediaLinks: 'http://twitter.com/artist8, http://instagram.com/artist8',
    //   numberOfPosts: 32,
    // },
    // {
    //   id: 9,
    //   userId: 109,
    //   biography: 'Utilizes mixed media to explore themes of identity and culture.',
    //   country: 'Brazil',
    //   birthDate: '1984-06-09',
    //   socialMediaLinks: 'http://instagram.com/artist9, http://linkedin.com/artist9',
    //   numberOfPosts: 19,
    // },
    // {
    //   id: 10,
    //   userId: 110,
    //   biography: 'Abstract painter known for bold colors and dynamic compositions.',
    //   country: 'Australia',
    //   birthDate: '1979-03-20',
    //   socialMediaLinks: 'http://facebook.com/artist10, http://twitter.com/artist10',
    //   numberOfPosts: 24,
    // },
    // {
    //   id: 11,
    //   userId: 111,
    //   biography: 'Photorealistic artist capturing the essence of everyday scenes.',
    //   country: 'Netherlands',
    //   birthDate: '1986-09-28',
    //   socialMediaLinks: 'http://instagram.com/artist11, http://linkedin.com/artist11',
    //   numberOfPosts: 21,
    // },
    // {
    //   id: 12,
    //   userId: 112,
    //   biography: 'Bold and expressive abstract expressionist.',
    //   country: 'Russia',
    //   birthDate: '1974-11-15',
    //   socialMediaLinks: 'http://twitter.com/artist12, http://facebook.com/artist12',
    //   numberOfPosts: 17,
    // },
    // {
    //   id: 13,
    //   userId: 113,
    //   biography: 'Creates ethereal landscapes with a focus on light and atmosphere.',
    //   country: 'Japan',
    //   birthDate: '1981-10-07',
    //   socialMediaLinks: 'http://instagram.com/artist13, http://twitter.com/artist13',
    //   numberOfPosts: 28,
    // },
    // {
    //   id: 14,
    //   userId: 114,
    //   biography: 'Illustrates whimsical characters and fantastical worlds.',
    //   country: 'South Korea',
    //   birthDate: '1976-12-23',
    //   socialMediaLinks: 'http://facebook.com/artist14, http://linkedin.com/artist14',
    //   numberOfPosts: 23,
    // },
    // {
    //   id: 15,
    //   userId: 115,
    //   biography: 'Abstract sculptor exploring the intersection of form and space.',
    //   country: 'China',
    //   birthDate: '1983-05-31',
    //   socialMediaLinks: 'http://instagram.com/artist15, http://twitter.com/artist15',
    //   numberOfPosts: 26,
    // },
  ];
  