// src/dummyData/dummyArtworks.ts

import { Artwork } from '../types/types';

export const dummyArtworks: Artwork[] = [
  {
    id: 1,
    title: 'Sunset Overdrive',
    description: 'A beautiful painting of a sunset over a cityscape.',
    categoryID: 1,
    authorId: 1,
    quantity: 5,
    price: 299.99,
    createdDate: '2023-05-01T08:30:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 2,
    title: 'Mountain Majesty',
    description: 'A stunning painting capturing the majesty of a mountain range.',
    categoryID: 1,
    authorId: 2,
    quantity: 3,
    price: 349.99,
    createdDate: '2023-06-15T09:00:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 3,
    title: 'Abstract Dreams',
    description: 'A vibrant abstract piece full of color and movement.',
    categoryID: 2,
    authorId: 3,
    quantity: 10,
    price: 199.99,
    createdDate: '2023-07-20T10:15:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 4,
    title: 'Seaside Serenity',
    description: 'A calming painting of a serene seaside view.',
    categoryID: 3,
    authorId: 4,
    quantity: 7,
    price: 249.99,
    createdDate: '2023-08-05T11:30:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 5,
    title: 'Night Sky',
    description: 'A mesmerizing painting of the night sky filled with stars.',
    categoryID: 4,
    authorId: 5,
    quantity: 6,
    price: 299.99,
    createdDate: '2023-09-10T12:45:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 6,
    title: 'Forest Whisper',
    description: 'A painting that captures the essence of a quiet forest.',
    categoryID: 5,
    authorId: 6,
    quantity: 4,
    price: 279.99,
    createdDate: '2023-10-25T14:00:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 7,
    title: 'Urban Jungle',
    description: 'A dynamic painting of a bustling urban environment.',
    categoryID: 6,
    authorId: 7,
    quantity: 8,
    price: 319.99,
    createdDate: '2023-11-15T15:30:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 8,
    title: 'Desert Mirage',
    description: 'A painting of a beautiful desert landscape with a mirage effect.',
    categoryID: 7,
    authorId: 8,
    quantity: 9,
    price: 259.99,
    createdDate: '2023-12-01T16:45:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 9,
    title: 'Ocean Depths',
    description: 'An intriguing painting depicting the mysterious depths of the ocean.',
    categoryID: 8,
    authorId: 9,
    quantity: 2,
    price: 349.99,
    createdDate: '2024-01-10T17:00:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 10,
    title: 'Eternal Spring',
    description: 'A painting celebrating the beauty of eternal spring.',
    categoryID: 9,
    authorId: 10,
    quantity: 12,
    price: 229.99,
    createdDate: '2024-02-14T18:15:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 11,
    title: 'Winter Wonderland',
    description: 'A painting capturing the serene beauty of a winter wonderland.',
    categoryID: 10,
    authorId: 11,
    quantity: 3,
    price: 269.99,
    createdDate: '2024-03-03T19:30:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 12,
    title: 'Autumn Bliss',
    description: 'A painting showcasing the warm colors of autumn.',
    categoryID: 11,
    authorId: 12,
    quantity: 5,
    price: 239.99,
    createdDate: '2024-04-20T20:45:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 13,
    title: 'Spring Awakening',
    description: 'A painting that brings the vibrancy of spring to life.',
    categoryID: 12,
    authorId: 13,
    quantity: 4,
    price: 299.99,
    createdDate: '2024-05-10T21:00:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 14,
    title: 'Summer Breeze',
    description: 'A painting that captures the essence of a gentle summer breeze.',
    categoryID: 13,
    authorId: 14,
    quantity: 6,
    price: 279.99,
    createdDate: '2024-06-01T22:15:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
  {
    id: 15,
    title: 'Hidden Waterfall',
    description: 'A painting revealing the beauty of a hidden waterfall.',
    categoryID: 14,
    authorId: 15,
    quantity: 7,
    price: 319.99,
    createdDate: '2024-07-20T23:30:00Z',
    userId: 1,
    firstName: 'Alex',
    lastName: 'Porrier',
    imageData: null,
    subCategoryIds: []
  },
];
